spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://mallonline-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}


## lb：表示负载均衡
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mallonline-gateway
server:
  port: 88
